using System;
using NUnit.Framework;

[TestFixture]
public class TestSummarizer
{

    // create a dummy body of text such as would be generated by TextGenerator
    // for some method


    [TestCase]
    public void SummarizeGeneratedText() { Assert.AreEqual(1, 2, "Not implemented."); }

}